apiVersion: batch/v1
kind: Job
metadata:
  name: test-carga
spec:
  template:
    spec:
      containers:
      - name: curl-test
        image: curlimages/curl:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            for i in $(seq 1 50); do
              curl -s http://app-ejemplo-service/ > /dev/null
              curl -s http://frontend/ > /dev/null
              sleep 2
            done
      restartPolicy: Never
  backoffLimit: 4
