name: CI/CD Pipeline para AKS

on:
  push:
    branches: [ main ]

env:
  REGISTRY: parcial2registry.azurecr.io
  IMAGE_NAME: app-ejemplo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login a Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}

    - name: Build y Push imagen a ACR
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: Login a Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy a AKS
      run: |
        az aks get-credentials --resource-group rg-aks-cluster --name aks-cluster --overwrite-existing
        kubectl set image deployment/app-ejemplo app-ejemplo=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} --record
        kubectl rollout status deployment/app-ejemplo
