name: CI/CD Pipeline con GHCR

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login a GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build y Push imagen
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/app-ejemplo:${{ github.sha }}
          ghcr.io/${{ github.repository }}/app-ejemplo:latest

    - name: Login a Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy a AKS
      run: |
        az aks get-credentials --resource-group rg-aks-cluster --name aks-cluster --overwrite-existing
        kubectl set image deployment/app-ejemplo app-ejemplo=ghcr.io/${{ github.repository }}/app-ejemplo:${{ github.sha }} --record
        kubectl rollout status deployment/app-ejemplo
