name: CI/CD Pipeline para AKS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        cd app-ejemplo
        docker build -t ghcr.io/${{ github.repository }}/app-ejemplo:${{ github.sha }} .
        docker build -t ghcr.io/${{ github.repository }}/app-ejemplo:latest .

    - name: Login to GitHub Container Registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}/app-ejemplo:${{ github.sha }}
        docker push ghcr.io/${{ github.repository }}/app-ejemplo:latest

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to AKS
      run: |
        az aks get-credentials --resource-group rg-aks-cluster --name aks-cluster --overwrite-existing
        kubectl set image deployment/app-ejemplo app-ejemplo=ghcr.io/${{ github.repository }}/app-ejemplo:${{ github.sha }} --record
        kubectl rollout status deployment/app-ejemplo

